apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-v1
  namespace: inference
  labels:
    app: ml-inference-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference-v1
  template:
    metadata:
      labels:
        app: ml-inference-v1
    spec:
      containers:
      - name: ml-inference
        image: ml-inference-v1:local
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

